### ISSUE TITLE
Can you remake this a clone of gorilla/websocket library?

### ISSUE THREAD

**Issue by tamalsaha** [fasthttp/websocket#1]
Hi,
Can you show this as a fork of gorilla/websocket library so that it is easy to understand how much it is behind/ahead/diff from the gorilla/websocket lib?

Thanks.

**Comment by kirillDanshin** [comment]
hi @tamalsaha 
you can diff it already by cloning both versions and running `diff` tool

**Comment by savsgio** [comment]
As @kirillDanshin says, you can see it with diff tool
