### ISSUE TITLE
Incorrect implementation of websocket upgrade header check

### ISSUE THREAD

**Issue by fangli** [fasthttp/websocket#11]
Hi,

The value of "Connection: Upgrade" and "Upgrade: websocket" should be treated as case INSENSITIVE but this library treats them case-sensitive.

Look at this:
https://github.com/fasthttp/websocket/blob/7eb5830af7/server_fasthttp.go#L144-L150

In IETF RFC6455 Section 4.2.1, https://tools.ietf.org/html/rfc6455#section-4.2.1
This field should be treated as an ASCII case-insensitive value.

Results:
This library responses 400 Bad Request when running behind AWS ALB, which use "Connection: upgrade" for any upgrade request.

**Comment by fangli** [comment]
For a better performance I'd like to fix this issue by allowing both "Upgrade" and "upgrade", both "Websocket" and "websocket".

I know this is tricky but it should solves 99.99% problem. at least it will work with AWS ALB.

**Comment by savsgio** [comment]
Hi @fangli,

Well seen. Please, make a PR and i will review it.

**Comment by fangli** [comment]
@savsgio See PR#12
Please note for a better performance I didn't implement them 100% RFC compatible.
But if this PR make the library compatible with nearly all web servers and proxies, I think it's acceptable.

**Comment by savsgio** [comment]
I've been fixed it, using ascii comparison!

Thanks!
