### ISSUE TITLE
Other upgraders?

### ISSUE THREAD

**Issue by betim** [fasthttp/websocket#14]
How do we upgrade a `*fasthttp.RequestCtx`??

**Comment by savsgio** [comment]
For upgrade connection:

```go
var upgrader = websocket.FastHTTPUpgrader{}

func example(ctx *fasthttp.RequestCtx) {
	err := upgrader.Upgrade(ctx, func(ws *websocket.Conn) {
		defer ws.Close()
		// .... your code
	})

	if err != nil {
		if _, ok := err.(websocket.HandshakeError); ok {
			log.Println(err)
		}
		return
	}
}
```

**Comment by betim** [comment]
Thanks for this. I could not find an example that explained it clearly and I think there should be one.

**Comment by savsgio** [comment]
You could check examples directory, that in each example have a fasthttp directory to see  how to use it
