### ISSUE TITLE
Upgrade synchronously

### ISSUE THREAD

**Issue by Fenny** [fasthttp/websocket#16]
When using upgrading with the gorilla library
```go
conn, err := upgrader.Upgrade(w, r, nil)
```

Using the fasthttp upgrader, we have a return function
```go
upgrader.Upgrade(fctx, func(conn *websocket.Conn) {
    // use conn
})
```

This works fine, but I was wondering if its possible to wrap this without being bound to the return function.
```go
var upgrader = websocket.FastHTTPUpgrader{}
func upgrade(fctx *fasthttp.RequestCtx) <-chan *websocket.Conn {
    channel := make(chan *websocket.Conn)
    go func() {
        defer close(channel)
	upgrader.Upgrade(ctx, func(conn *websocket.Conn) {
	    channel <- conn
        })
    }()
    return channel
}
conn := <-upgrade(fctx)
// <nil>
```

**Comment by erikdubbelboer** [comment]
I haven't tested your code but are you sure this works? fasthttp won't call the hijack function until the handler has returned. So if I understand correctly the code in your fasthttp handler is going to wait to read from the channel. But the channel won't be written to before the handler has returned. Causing a deadlock.

**Comment by savsgio** [comment]
By design of fasthttp you couldn't get the websocket connection synchronously due to @erikdubbelboer  says.

I tested your code and the handler produce a deadlock or the returned value of the channel it's always nil.

**Comment by savsgio** [comment]
The difference between `net/http` and `fasthttp`  is that `net/http` hijack the connection when you call to `w.(http.Hijacker).Hijack()` immediately, but in `fasthttp` the hijacked connection it's got when the handler is returned and execute the callback function declared in `ctx.Hijack(func(netConn net.Conn) { ... })`

**Comment by Fenny** [comment]
I understand now why it's not possible, thanks for the explanation!
