### ISSUE TITLE
Possible to support "nhooyr/websocket" then gorilla/websocket ?

### ISSUE THREAD

**Issue by rebootcode** [fasthttp/websocket#18]
https://github.com/nhooyr/websocket is much better than gorilla/websocket.

Is it possible to have fasthttp support for that?

**Comment by dgrr** [comment]
Hello,

This library is intended to be used as a standard fasthttp's websocket. If you are looking for performance in any way, you can use [this](https://github.com/fasthttp/fastws) websocket package.

So, in reply to you question: We aren't going to add support for that library as long as we already have 2 libraries: one focused on performance and the other one focused on compatibility with net/http libraries.

**Comment by rebootcode** [comment]
That solves the issue. Was not aware of `fastws`
