### ISSUE TITLE
Re-uploading v1.4.2 has introduced checksum mismatch

### ISSUE THREAD

**Issue by sylvain-p85** [fasthttp/websocket#20]
In the release section, it is written that the version 1.4.2 has been re-uploaded. This has introduced some install failures : 

```bash
verifying github.com/fasthttp/websocket@v1.4.2: checksum mismatch
 	downloaded: h1:AU/zSiIIAuJjBMf5o+vO0syGOnEfvZRu40xIhW/3RuM=
 	go.sum:     h1:hTnl0DRQ9Tj4uVc4QcZCGp+mgF5mVKnijR1eNyn2waY=
 SECURITY ERROR
 This download does NOT match an earlier download recorded in go.sum.
 The bits may have been replaced on the origin server, or an attacker may
 have intercepted the download attempt.
 For more information, see 'go help module-auth'.
```

In my company, we are currently using internal go proxy based on JFrog. Even if I remove entries in my project go.sum, it is still failing. If I'm using golang proxy and removing these entries, it is working. 

Unfortunately, our CI is using our internal proxy and we are completely stuck.

Is it possible for you to release a new tag `v1.4.3`in order to fix it ? Thx.

**Comment by savsgio** [comment]
Hi @sylvain-p85,

Sorry for delayed answer.

You could upgrade to last version [v1.4.3-beta.1](https://github.com/fasthttp/websocket/releases/tag/v1.4.3-beta.1)
Don't worry about `beta` tag because it's a pre-release to keep the same versioning of `gorilla/websocket`, so it's an stable release 😉
