### ISSUE TITLE
IsWebsocketUpgrade returning false

### ISSUE THREAD

**Issue by Nv7-GitHub** [fasthttp/websocket#24]
The IsWebsocketUpgrade function is returning false, leading to the server returning a 426. You can try this out by going to https://www.websocket.org/echo.html and putting in the location as `wss://api.nv7haven.tk/ws/123?v=1.0`. Any ideas why this could be happening?

**Comment by savsgio** [comment]
Hi @Nv7-GitHub,

I've checked it now and it works! 🤔

**Comment by Nv7-GitHub** [comment]
For me its instantly closing, is it working for you?

**Comment by savsgio** [comment]
<img width="759" alt="Captura de pantalla 2021-03-17 a las 16 53 56" src="https://user-images.githubusercontent.com/13466135/111497439-6611d200-8741-11eb-9b1a-67fbeee2dbd9.png">
