### ISSUE TITLE
Replace flate with the flate pool from fasthttp

### ISSUE THREAD

**Issue by mertakman** [fasthttp/websocket#26]
Fast HTTP is using well-optimized https://github.com/klauspost/compress library for compression. I think we can change it in here too, with that way we can get very nice performance and resource optimization for websocket connections with compression.

**Comment by savsgio** [comment]
Hi @mertakman,

Sorry for delayed answer!

Could you make a PR please?

**Comment by savsgio** [comment]
Hi @mertakman,

Changed the library in [v1.5.1-rc.9](https://github.com/fasthttp/websocket/releases/tag/v1.5.1-rc.9).

Thanks for your suggest!
