### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by kuchaguangjie** [fasthttp/websocket#29]
When using `fiber/websocket`, which in turn use `fasthttp/websocket`, I get following errors:

```
panic: concurrent write to websocket connection

goroutine 31 [running]:
github.com/fasthttp/websocket.(*messageWriter).flushFrame(0xc00032c240, 0x1, {0x0?, 0x7f3a1327ca68?, 0x30?})
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/conn.go:617 +0x52b
github.com/fasthttp/websocket.(*messageWriter).Close(0x0?)
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/conn.go:731 +0x45
github.com/fasthttp/websocket.(*Conn).beginMessage(0xc0000bd080, 0xc00043f1a0, 0x1)
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/conn.go:480 +0x42
github.com/fasthttp/websocket.(*Conn).NextWriter(0xc0000bd080, 0x1)
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/conn.go:520 +0x45
github.com/fasthttp/websocket.(*Conn).WriteJSON(0xc000019a80?, {0xb34be0, 0xc000367c40})
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/json.go:24 +0x45

github.com/deckarep/golang-set.(*threadSafeSet).Each(0xc0004445e0, 0xc00043f170)
	/home/eric/go/pkg/mod/github.com/deckarep/golang-set@v1.8.0/threadsafe.go:157 +0xaf

github.com/gofiber/websocket/v2.New.func2.4(0x0?)
	/home/eric/go/pkg/mod/github.com/gofiber/websocket/v2@v2.0.22/websocket.go:109 +0x75
github.com/fasthttp/websocket.(*FastHTTPUpgrader).Upgrade.func1({0xd52d50, 0xc0000a9770})
	/home/eric/go/pkg/mod/github.com/fasthttp/websocket@v1.5.0/server_fasthttp.go:201 +0x1ad
github.com/valyala/fasthttp.hijackConnHandler(0x0?, {0xd4b3c0?, 0xc000412cc0}, {0xd52f08, 0xc0001a2130}, 0xc0001cbd40, 0xc000367580)
	/home/eric/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/server.go:2479 +0x68
created by github.com/valyala/fasthttp.(*Server).serveConn
	/home/eric/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/server.go:2434 +0x1d85
exit status 2
```

There are 2 go-routines write to the websocket connection. I know cause of the issue is concurrent write on the connection.

I got 2 ideas on how this maybe fixed:
1. Use a mutex, acquire the lock before write, release the lock after write.
2. Use a channel to store messages, then use a single go routine to read from the channel, and write those messages.

Any  suggestion on which of the solution is better, or there are other solutions?

**Comment by kuchaguangjie** [comment]
I've implemented the mutex solution, I need to lock on all write & close operations, to avoid the `concurrent write` error.
Seems close operation will also write to the connection.
Wondering the performance impact of this solution, compared to the version without mutex.

**Comment by savsgio** [comment]
Hi @kuchaguangjie,

Sorry for my delayed answer!

The library doesn't support concurrent read/writes. (https://pkg.go.dev/github.com/gorilla/websocket?utm_source=godoc#hdr-Concurrency).

**Comment by kuchaguangjie** [comment]
Ok, it's using `gorilla/websocket` underneath? But I didn't see that in `go.mod`.

**Comment by kuchaguangjie** [comment]
Ok, I get it from README `Gorilla WebSocket implementation for fasthttp.`

**Comment by savsgio** [comment]
Yes, It is a fork that only adds support to fasthttp 😉
