### ISSUE TITLE
Since gorilla projects are archived, how would it impact this project ?

### ISSUE THREAD

**Issue by kuchaguangjie** [fasthttp/websocket#32]
Refer: https://github.com/gorilla#gorilla-toolkit

Questions:
- Since there is no more update to gorilla/websocket, will fasthttp/websocket keep improve & fix bug ?

**Comment by savsgio** [comment]
Hello @kuchaguangjie and community!

Until further notice, we will continue to improve and fix bugs as much as possible. Don't worry! 😄
So, until now, this project was aligned with gorilla in releases, but from now, it will be released independently.

Thank you very much for everything 😉

**Comment by heitorPB** [comment]
How will this project move forward now that Gorilla was unarchived?
