### ISSUE TITLE
Is there any plan to support websocket client of fasthttp?

### ISSUE THREAD

**Issue by Quons** [fasthttp/websocket#36]
I am focus on a websocket proxy gateway works，so i need both server and client of websocket. but i  notidy that this project support only server side of websocket base on fasthttp，is there  any plan to support the client side ?

**Comment by savsgio** [comment]
Hi @Quons,

I don't rule it out, but for now, i don't have to much time to add support to the client.
So, if you need it, a PR is welcome! 😉

**Comment by g41797** [comment]
Hi
As far as i understand , websocket client (fork of gorilla...) is part of this project and everyone can use it ,
[savsgio](https://github.com/savsgio) - please confirm

**Comment by joeky888** [comment]
I can confirm fasthttp websocket client with http proxy works. Tested with https://github.com/joeky888/fpgo

```go
dialer := websocket.Dialer{
	Proxy: http.ProxyURL(&url.URL{
		Scheme: "http", // or "https" depending on your proxy
		Host:   "127.0.0.1:13002",
		Path:   "/",
	}),
}

c, _, err := dialer.Dial("wss://ws.bitget.com/mix/v1/stream", nil)
if err != nil {
	log.Fatal("dial:", err)
}
defer c.Close()
```

I guess we can close this issue, unless I missed something.

**Comment by g41797** [comment]
you did

fasthttp/websocket is fork of non-maintained [gorilla/websocket](https://github.com/gorilla/websocket)
gorilla/websocket has 28 opened issues and 12 PRs

- "what about unresolved issues and PRs?" 
- "are you going to announce fasthttp as new maintainer of websocket?"

**Comment by savsgio** [comment]
Hi @g41797 and @joeky888, 

I'm trying to maintain the fork as much I can. So if you need to resolve some issue from gorilla project and it be here, you can make a PR about it or create an issue here to try to fix it.

PR are always welcome. 😉 

Thank you so much! And sorry for my delayed answer!
