### ISSUE TITLE
fasthttp/websocket doesnt work with nats.io 

### ISSUE THREAD

**Issue by hiqbn** [fasthttp/websocket#4]
my code is here:
https://pastebin.com/raw/hURatUqs

failed at 

         conn.WriteMessage(websocket.TextMessage []byte(s))

if will work if i comment 

               nc.Subscribe(subj, func(

so i don't understand why they cant work together

===================

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x75e3b2]

goroutine 61 [running]:
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc007ef0a00, 0x0, 0x0, 0x0, 0xc0000aa000, 0x203001)
        <autogenerated>:1 +0x32
github.com/fasthttp/websocket.(*Conn).write(0xc0067dc420, 0x1, 0x0, 0x0, 0x0, 0xc007efa90c, 0x3, 0x402, 0xc0075156b1, 0x0, ...)
        /go/src/github.com/fasthttp/websocket/conn.go:376 +0xfb
github.com/fasthttp/websocket.(*messageWriter).flushFrame(0xc00680fec8, 0xc007515601, 0xc0075156b1, 0x0, 0x7, 0x8, 0xc0075156b0)
        /go/src/github.com/fasthttp/websocket/conn.go:601 +0x23d
github.com/fasthttp/websocket.(*Conn).WriteMessage(0xc0067dc420, 0x1, 0xc0075156b0, 0x1, 0x8, 0x8, 0x0)
        /go/src/github.com/fasthttp/websocket/conn.go:753 +0x24b
main.requestHandler.func1.1(0xc007f2c000)
        /usr/local/src/programs/r/r.go:496 +0xd1
github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc007f04000, 0xc0044003c0)
        /go/src/github.com/nats-io/go-nats/nats.go:2024 +0x258
created by github.com/nats-io/go-nats.(*Conn).subscribe
        /go/src/github.com/nats-io/go-nats/nats.go:2789 +0x460

**Comment by savsgio** [comment]
Hi @hiqbn,

This panic is triggered because the connection is closed inside `nc.Subscribe`.

The websocket's handler must need to keep the connection alive, if you don't do this, the connection is close automatically.
So, in your case, I suggest you to use `sync.WaitGroup`.

For example:

```go
err := upgrader.Upgrade(ctx, func(conn *websocket.Conn) {
        //                      ... Use conn to send and receive messages.


        //                      for {
        //                              messageType, p, err := conn.ReadMessage()
        //                              if err != nil {
        //                                      log.Println(err)
        //                                      return
        //                              }
        //if err := conn.WriteMessage(1, p); err != nil {

        // This help you to keep connection alive
        var wg sync.WaitGroup

        i:=0
        nc, err1 := nats.Connect("nats://127.0.0.1:75")
        if err1 != nil {
                log.Fatal(err1)
        }

        subj := "t"
        
        wg.Add(1) // Only add 1 per nc.Subscribe()
        nc.Subscribe(subj, func(msg *nats.Msg) {
                // Check when you need to close websocket connection and exit
                if i > 200 { // Condition example
                        wg.Done()
                        // Unsubscribe If you need
                        ....
                        return
                }

                i++
                s:=strconv.Itoa(i)
                m, _ := time.ParseDuration("1s") //read from local file
                time.Sleep(m)
                conn.WriteMessage(websocket.TextMessage, []byte(s))
        })

        defer nc.Flush()

        // This keep the connection alive until wg.Done()
        wg.Wait()
})
```


It's possible that I have a code syntax errors, I wrote with my mobile phone ;)

**Comment by savsgio** [comment]
@hiqbn had you could to solve it?

**Comment by hiqbn** [comment]
Let me try first. Sorry. Give me 2 days

**Comment by hiqbn** [comment]
This is very good. What's the normal way to check if the client websocket connection is disconnected?
instead of                 

                      if i > 200 { // Condition example

what's the proper way to detect disconnection etc?

**Comment by hiqbn** [comment]
the problem i'm having now with i > 200 is, once i > 200, it'll crash with this error

panic: sync: negative WaitGroup counter

goroutine 93 [running]:
sync.(*WaitGroup).Add(0xc007e65550, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x137
sync.(*WaitGroup).Done(0xc007e65550)
        /usr/local/go/src/sync/waitgroup.go:99 +0x34
main.requestHandler.func1.1(0xc006944500)
        /usr/local/src/programs/r/r.go:497 +0x42
github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc007524580, 0xc006870900)
        /go/src/github.com/nats-io/go-nats/nats.go:2024 +0x258
created by github.com/nats-io/go-nats.(*Conn).subscribe
        /go/src/github.com/nats-io/go-nats/nats.go:2789 +0x460

**Comment by hiqbn** [comment]
once counter hit >200,

it will crash at

**Comment by hiqbn** [comment]
once counter hit >200,

it will crash at    

wg.Done()

**Comment by hiqbn** [comment]
basically i think i got most parts working. how do i detect a client disconnection?

**Comment by hiqbn** [comment]
is this the answer?
https://github.com/valyala/fasthttp/issues/362

**Comment by savsgio** [comment]
Please, could you shared your new code?

**Comment by hiqbn** [comment]
I'm not sure how to detect a client disconnect or what to do after a client disconnect

https://pastebin.com/ejf3Ud0N

**Comment by savsgio** [comment]
> the problem i'm having now with i > 200 is, once i > 200, it'll crash with this error
> 
> panic: sync: negative WaitGroup counter
> 
> goroutine 93 [running]:
> sync.(*WaitGroup).Add(0xc007e65550, 0xffffffffffffffff)
> /usr/local/go/src/sync/waitgroup.go:74 +0x137
> sync.(*WaitGroup).Done(0xc007e65550)
> /usr/local/go/src/sync/waitgroup.go:99 +0x34
> main.requestHandler.func1.1(0xc006944500)
> /usr/local/src/programs/r/r.go:497 +0x42
> github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc007524580, 0xc006870900)
> /go/src/github.com/nats-io/go-nats/nats.go:2024 +0x258
> created by github.com/nats-io/go-nats.(*Conn).subscribe
> /go/src/github.com/nats-io/go-nats/nats.go:2789 +0x460

This is only a condition example. 
It crashed because the `wg.Done()` has been executed more than once. Remeber `wg.Add(1) // Only add 1 per nc.Subscribe()`

**Comment by savsgio** [comment]
> basically i think i got most parts working. how do i detect a client disconnection?

Please read this:
https://github.com/gorilla/websocket/issues/34

**Comment by savsgio** [comment]
And add `conn.Close()` after this line :smile: 
```go
err := upgrader.Upgrade(ctx, func(conn *websocket.Conn) {
    defer conn.Close()  // Ensure closed connection
    ...
```

**Comment by hiqbn** [comment]
thx! great help. i wish there were more examples / docs and explanations online.
