### ISSUE TITLE
how do i detect a client disconnection?

### ISSUE THREAD

**Issue by hiqbn** [fasthttp/websocket#5]
I saw this to handle client disconnect.

               Please read this:
               gorilla/websocket#34

               https://github.com/gorilla/websocket/blob/master/examples/chat/client.go

i'm curious if there's an easier way to do this ping pong thing. any other elegant examples with lesser code?

with reference to this
https://github.com/valyala/fasthttp/issues/362

**Comment by savsgio** [comment]
You could read the cliente disconnection message, and check error variable returned by conn.ReadMesage() with this: https://github.com/fasthttp/websocket/blob/master/conn.go#L150
