### ISSUE TITLE
I had write a websocket proxy ,but I find in Upgrade method FastHTTPHandler func miss ctx's value

### ISSUE THREAD

**Issue by 59duncom** [fasthttp/websocket#9]
https://github.com/valyala/fasthttp/issues/597
this is the issues,but I find in 	upgrader.Upgrade(ctx,func(ws *websocket.Conn) { 
fmt.Println(string(ctx.RequestURI())) //here the ctx is not fill with value ,the value is the correct
})

**Comment by 59duncom** [comment]
https://s2.ax1x.com/2019/07/02/ZJIS0O.png

**Comment by dgrr** [comment]
As I said here https://github.com/valyala/fasthttp/issues/597 I think the error is from the fasthttp code.

**Comment by 59duncom** [comment]
how to get the correct ctx.RequestURI() ,I will use in ws proxy as a client

**Comment by dgrr** [comment]
You can save the values before upgrading. Or make a copy of the request:
```go
req := fasthttp.AcquireRequest()
defer fasthttp.ReleaseRequest(req)

ctx.Request.CopyTo(req)
(upgrade)
```

**Comment by 59duncom** [comment]
ok ，thanks
